# -*- coding: utf-8 -*-
"""test_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5096fPwhNjKcoZ5Jdp4ms--fiTJbAgq
"""

import requests

sample_passenger = {
    "Pclass": 3,
    "Age_imputed": 22.0,
    "SibSp": 1,
    "Parch": 0,
    "Fare_imputed": 7.25,
    "SexVec": [1.0, 0.0],
    "EmbarkedVec": [0.0, 1.0, 0.0]
}

response = requests.post("http://127.0.0.1:8000/predict", json=sample_passenger)
print(response.json())